name: Close Inactive Issues

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7
          days-before-close: 0
          stale-issue-message: "This issue has been marked as stale due to 7 days of inactivity and will now be closed."
          close-issue-reason: "not_planned"
          stale-issue-label: "stale"
